### ISSUE TITLE
Missing exe from the tools folder

### ISSUE THREAD

**Issue by teroz** [brandonlw/Psychson#1]
Thank you for the release and for the documenting  on the wiki. tools\DriveCom.exe is mentioned in the wiki but is not exist.

**Comment by Burn3diC3** [comment]
You'll need to build it yourself using Visual Studio. Open DriveCom\DriveCom.sln with Visual Studio and then build it.

**Comment by Dionesz23** [comment]
Visual Studio Express 2012 for Windows
http://www.microsoft.com/en-us/download/details.aspx?id=34673

**Comment by GulfBull** [comment]
Confirmed to compile flawlessly with VS2013.

**Comment by war59312** [comment]
Might as well just release as exe too as surly someone else will.

Better off having an "offical" download.

Just saying. Built fine myself.

**Comment by senjuhashirama** [comment]
Compiled On Visual Studio 2015 Community RC .
