### ISSUE TITLE
Burner Image

### ISSUE THREAD

**Issue by dyl10s** [brandonlw/Psychson#106]
I really need help to find out how to get this burner image in so confused! I have done everything but this!

**Comment by lrp1985** [comment]
I recommend to you to follow this tutorial is very well explained step by step process.

http://www.pentestingshop.com/pentesting/make-your-own-usb-rubber-ducky-using-a-normal-usb-stick/

**Comment by RedToor** [comment]
somebody have the binaries for badusb?
