### ISSUE TITLE
Reported chip type: 0000

### ISSUE THREAD

**Issue by mtfurlan** [brandonlw/Psychson#11]
Greetings. I have a Patriot 8GB Supersonic Xpress drive, as recommended.

Output of `GetInfo` is 

```
$ ./DriveCom/DriveCom/obj/Debug/DriveCom.exe /drive=F /action=GetInfo
Action specified: GetInfo
Gathering information...
Reported chip type: 0000
Reported chip ID: 98-D7-94-32-76-56
Reported firmware version: 1.11.10
Mode: Unknown
```

As I didn't know that the output of reported chip ID should actually be useful, I opened it up to find the controller version, and the top of the chip says 

```
PHISON
PS2251-01-M
RE1219C
3B1YV81421CB
```

Armed with the knowledge, I got the file marked `Firmware PS2251-01 [BN01*.BIN, FW01*.BIN]` off the [page in useful links](http://www.usbdev.ru/files/phison/).
It does not adhere to the naming conventions mentioned on the [Obtaining a Burner Image](https://github.com/adamcaudill/Psychson/wiki/Obtaining-a-Burner-Image) page.
I then did the `SetBootMode`, and then tried to dump the firmware.
I compiled DriveCom in visual studio professional 2013.

```
mark@Sanguine /cygdrive/c/Users/mark/Desktop/usb shenanagans/Psychson-master
$ ./DriveCom/DriveCom/obj/Debug/DriveCom.exe /drive=F /action=SetBootMode
Action specified: SetBootMode

mark@Sanguine /cygdrive/c/Users/mark/Desktop/usb shenanagans/Psychson-master
$ ./DriveCom/DriveCom/obj/Debug/DriveCom.exe /drive=F /action=SendExecutable /burner=../BN01V_UNK1.BIN
Action specified: SendExecutable
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0079
   at DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte[] data, Int32 bytesExpected) in c:\Users\mark\Desktop\usb shenanagans\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 365
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Int32 bytesExpected) in c:\Users\mark\Desktop\usb shenanagans\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 295
   at DriveCom.PhisonDevice.TransferFile(Byte[] data, Byte header, Byte body) in c:\Users\mark\Desktop\usb shenanagans\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 249
   at DriveCom.PhisonDevice.TransferFile(Byte[] data) in c:\Users\mark\Desktop\usb shenanagans\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 238
   at DriveCom.Startup._ExecuteImage(String fileName) in c:\Users\mark\Desktop\usb shenanagans\Psychson-master\DriveCom\DriveCom\Startup.cs:line 403
   at DriveCom.Startup.Main(String[] args) in c:\Users\mark\Desktop\usb shenanagans\Psychson-master\DriveCom\DriveCom\Startup.cs:line 109
```

At this point I went looking for more information.
I tried the reset tool [mentioned](https://github.com/adamcaudill/Psychson/wiki/Restoring-to-Stock-Firmware) on the wiki, no difference.

**Comment by mtfurlan** [comment]
Fascinatingly, if I do `GetInfo` _after_ `SetBootMode`, I get different results

```
$ ./DriveCom/DriveCom/obj/Debug/DriveCom.exe /drive=F /action=GetInfo
Action specified: GetInfo
Gathering information...
Reported chip type: 2301
Reported chip ID: 98-D7-94-32-76-56
Reported firmware version: 1.04.10
Mode: Firmware
```

**Comment by DevPGSV** [comment]
For me, the only way to get in Boot Mode is to do a "/action=SendFirmware",...
It doesn't matter when I do it, the line "Reported chip type: [whatever]" doesn't appear... :(

I have a Kingstone DataTraveler (2G):
![](http://www.bestunion-tech.com/bigpic/20091005090623.jpg)

I guess i won't work for me, since it's not 3.0

**Comment by brandonlw** [comment]
Scuzzball, with yours being controller version 01 (instead of 03), I doubt it's going to work. But I'm puzzled by the chip type 0000, though...my guess is that your particular firmware version stores that information in a different location in the vendor data returned. That's good to know.

**Comment by mtfurlan** [comment]
Okay, might want to make a note on the supported devices page that not all of the Patriot 8GB Supersonic Xpress drives work, and mention the version thing on the page too.
Either way, thanks for the help, and I'll look into buying a new one.

**Comment by entangledloops** [comment]
I get different results for every run on the same USB. This is replicated across multiple USBs. The device ID is always 0000 and the process DriveCom.vs.exe persists after execution completes as a background process. I'm using the Sandisk Ultra 3.0 USB ZF48, which is listed as supported.
