### ISSUE TITLE
PSF16GXPUSB

### ISSUE THREAD

**Issue by pascalpfeil** [brandonlw/Psychson#13]
Patriot Supersonic Xpress - PSF16GXPUSB 16GB USB3

will this one work, too?

**Comment by brandonlw** [comment]
I'm afraid there's no way to know without first using DriveCom or another utility to see what controller version, NAND chip, and firmware version it has.

**Comment by pascalpfeil** [comment]
Can you add a detailed tutorial for identifying those to the wiki and how to determine which drives are compatible? i got like 5 different drives lying around...

**Comment by cubic3d** [comment]
It's described [here](https://github.com/adamcaudill/Psychson/wiki/Setting-Up-the-Environment).

**Comment by llamasoft** [comment]
@CuBiC3D - Maybe you should update the wiki page to include more information on what to look for and how to use the information that DriveCom gives you.

For example, the output of running `GetInfo` on my USB drive shows:

```
Action specified: GetInfo
Gathering information...
Reported chip type: 2307
Reported chip ID: AD-DE-94-DA-74-C4
Reported firmware version: 1.04.10
Mode: Firmware
```

Without a comparison of what to expect, the above information means almost nothing to an inexperienced user.  (The above information corresponds to an incompatible PS2251-07 Kingston DataTraveler)

**Comment by pascalpfeil** [comment]
@llamasoft the bad thing is that even if you buy a confirmed device, you might end up getting an incompatible device because the controllers vary with same device models (sorry for the poor english)
