### ISSUE TITLE
Cheap USB drive that is compatible  

### ISSUE THREAD

**Issue by DarrenRainey** [brandonlw/Psychson#143]
What is the cheapest usb drive that will work with this code ?

**Comment by TotalDay** [comment]
Sandisk SDCZ48-016G

PS2251-03

https://goo.gl/88ASp7

Toshiba V3SZK-032G

PS2251-03

https://goo.gl/L0EK7u

**Comment by michelecampobasso** [comment]
Did anybody checked if those are actually ok?

**Comment by TotalDay** [comment]
https://goo.gl/NisgFx

**Comment by 3ntr0phy** [comment]
The first two linked are not OK,I bought them but the controller is not correct. Are you sure about the new link Bro?
