### ISSUE TITLE
Patriot 8GB Express USB 3.0

### ISSUE THREAD

**Issue by ghost** [brandonlw/Psychson#158]
Hello guys,
I wonder if the model below, it will run the code.

http://www.americanas.com.br/produto/111991151/pen-drive-8gb-patriot-express-usb-3.0?epar=buscape&opn=YYNKZB&loja=02&s_term=YYNKZB#productdetails

http://www.shoptime.com.br/produto/111991151/pen-drive-8gb-patriot-express-usb-3.0?opn=BUSCAPE&loja=01&epar=4024&s_term=BUSCAPE

For I saw the "Patriot Supersonic Xpress 8GB \* (Almost all are now in 2307 on Amazon [bought 9 from 9 all sellers])" and was in doubt.

Is there any way to know whether it will work, the bar code? (815530011828)

And the only ones found in Brazil.

**Comment by TotalDay** [comment]
https://goo.gl/NisgFx
