### ISSUE TITLE
Hidden Partition Patch

### ISSUE THREAD

**Issue by groverito** [brandonlw/Psychson#16]
I do not understand Hidden Partition Patch help.

I see no usb partition = 0mb

**Comment by groverito** [comment]
**\* Generating C .h file...
Action: GenerateHFile
Firmware image: fw.bin
WARNING! This firmware version has not been verified to work with these patches.

Output file: equates.h
Generating .h file...
Done.
**\* Building base.c...
base.c:190: error 20: Undefined identifier 'scsi_cdb'
base.c:190: error 22: Array or pointer required for '[]' operation
base.c:194: error 20: Undefined identifier 'scsi_cdb'
base.c:194: error 22: Array or pointer required for '[]' operation
base.c:198: error 20: Undefined identifier 'scsi_cdb'
base.c:198: error 22: Array or pointer required for '[]' operation
base.c:198: error 20: Undefined identifier 'scsi_cdb'
base.c:198: error 22: Array or pointer required for '[]' operation
base.c:198: error 78: incompatible types
from type 'void'
  to type 'volatile-unsigned-char xdata\* fixed'
base.c:204: error 20: Undefined identifier 'scsi_cdb'
base.c:204: error 22: Array or pointer required for '[]' operation
base.c:204: error 20: Undefined identifier 'scsi_cdb'
base.c:204: error 22: Array or pointer required for '[]' operation
base.c:204: error 78: incompatible types
from type 'void'
  to type 'volatile-unsigned-char xdata\* fixed'
base.c:204: error 20: Undefined identifier 'scsi_cdb'
base.c:204: error 22: Array or pointer required for '[]' operation
base.c:210: error 20: Undefined identifier 'scsi_cdb'
base.c:210: error 22: Array or pointer required for '[]' operation
base.c:210: error 27: Pointer required
base.c:216: error 20: Undefined identifier 'scsi_cdb'
base.c:216: error 22: Array or pointer required for '[]' operation
base.c:216: error 27: Pointer required
base.c:216: error 20: Undefined identifier 'scsi_cdb'
base.c:216: error 22: Array or pointer required for '[]' operation
base.c:239: error 20: Undefined identifier 'scsi_cdb'
base.c:239: error 22: Array or pointer required for '[]' operation
base.c:239: error 43: invalid operand for shift operator
base.c:239: warning 113: left & right types are
void,const-unsigned-char literal
base.c:239: error 47: indirections to different types assignment
from type 'void'
  to type 'unsigned-long-int fixed'
base.c:240: error 20: Undefined identifier 'scsi_cdb'
base.c:240: error 22: Array or pointer required for '[]' operation
base.c:240: error 43: invalid operand for shift operator
base.c:240: warning 113: left & right types are
void,const-unsigned-char literal
base.c:240: error 45: operand invalid for bitwise operation
base.c:240: warning 113: left & right types are
unsigned-long-int fixed,void
base.c:241: error 20: Undefined identifier 'scsi_cdb'
base.c:241: error 22: Array or pointer required for '[]' operation
base.c:241: error 45: operand invalid for bitwise operation
base.c:241: warning 113: left & right types are
void,const-int literal
base.c:241: error 47: indirections to different types assignment
from type 'void'
  to type 'unsigned-long-int fixed'
base.c:242: error 20: Undefined identifier 'scsi_cdb'
base.c:242: error 22: Array or pointer required for '[]' operation
base.c:242: error 47: indirections to different types assignment
from type 'void'
  to type 'unsigned-long-int fixed'
base.c:251: error 20: Undefined identifier 'scsi_cdb'
base.c:251: error 22: Array or pointer required for '[]' operation
base.c:252: error 20: Undefined identifier 'scsi_cdb'
base.c:252: error 22: Array or pointer required for '[]' operation
base.c:253: error 20: Undefined identifier 'scsi_cdb'
base.c:253: error 22: Array or pointer required for '[]' operation
base.c:254: error 20: Undefined identifier 'scsi_cdb'
base.c:254: error 22: Array or pointer required for '[]' operation
base.c:265: error 20: Undefined identifier 'scsi_cdb'
base.c:265: error 22: Array or pointer required for '[]' operation
base.c:317: error 20: Undefined identifier 'scsi_cdb'
base.c:317: error 22: Array or pointer required for '[]' operation
base.c:317: error 43: invalid operand for shift operator
base.c:317: warning 113: left & right types are
void,const-unsigned-char literal
base.c:317: error 47: indirections to different types assignment
from type 'void'
  to type 'unsigned-long-int fixed'
base.c:318: error 20: Undefined identifier 'scsi_cdb'
base.c:318: error 22: Array or pointer required for '[]' operation
base.c:318: error 43: invalid operand for shift operator
base.c:318: warning 113: left & right types are
void,const-unsigned-char literal
base.c:318: error 45: operand invalid for bitwise operation
base.c:318: warning 113: left & right types are
unsigned-long-int fixed,void
base.c:319: error 20: Undefined identifier 'scsi_cdb'
base.c:319: error 22: Array or pointer required for '[]' operation
base.c:319: error 45: operand invalid for bitwise operation
base.c:319: warning 113: left & right types are
void,const-int literal
base.c:319: error 47: indirections to different types assignment
from type 'void'
  to type 'unsigned-long-int fixed'
base.c:320: error 20: Undefined identifier 'scsi_cdb'
base.c:320: error 22: Array or pointer required for '[]' operation
base.c:320: error 47: indirections to different types assignment
from type 'void'
  to type 'unsigned-long-int fixed'
base.c:329: error 20: Undefined identifier 'scsi_cdb'
base.c:329: error 22: Array or pointer required for '[]' operation
base.c:330: error 20: Undefined identifier 'scsi_cdb'
base.c:330: error 22: Array or pointer required for '[]' operation
base.c:331: error 20: Undefined identifier 'scsi_cdb'
base.c:331: error 22: Array or pointer required for '[]' operation
base.c:332: error 20: Undefined identifier 'scsi_cdb'
base.c:332: error 22: Array or pointer required for '[]' operation
**\* There were errors! ***
**\* Done.

I do not understand Hidden Partition Patch.

 help

**Comment by aminazek** [comment]
@groverito 

I got the same error too. And it is true that scsi_cdb is not declared anywhere the code. 

Did you manage to compile and generate patch?

**Comment by brandonlw** [comment]
You will get compile errors if it is unable to determine patch locations for the firmware you specified.

The "WARNING! This firmware version has not been verified to work with these patches." message indicates this is not 1.03.53, which is the only firmware version verified to work.
