### ISSUE TITLE
CFW.bin on IDA PRO

### ISSUE THREAD

**Issue by cevrbt** [brandonlw/Psychson#17]
I wish i could open the firmware, patched and/or the stock one with IDA, but the CFW is recognized as binary, where the autoanalysis have to start? what's the address?
Thanks

**Comment by linuxFR** [comment]
You must change the processor type to Intel 8051.

**Comment by brandonlw** [comment]
Some additional information:

All firmware is split into multiple sections:

Header (0x200 bytes) (this is not loaded into memory)
Base section (0x6000 bytes)
Section 0 (0x4000 bytes)
Section 1 (0x4000 bytes)
...
Section n (0x4000 bytes)
Footer (0x200 bytes) (this is not loaded into memory)

All of the non-base sections are loaded to address 0x5000.
