### ISSUE TITLE
What about ubuntu and other *nix systems?

### ISSUE THREAD

**Issue by WhiteLedAnn** [brandonlw/Psychson#2]
It have anyway to run on it(*nix) witout using wine or smting like this?
Or need to rewrite code for it?

(psSorry for my bad English)

**Comment by ghost** [comment]
Currently the tools are focused on Windows systems - we are talking about porting them to something more cross-platform friendly, but don't have anything ready to be made public yet.

**Comment by Zolmeister** [comment]
+1
