### ISSUE TITLE
"Unknown device" DT100 16GB bricked ?

### ISSUE THREAD

**Issue by SrMilton** [brandonlw/Psychson#206]
heyy boysssss. I have a Kingston DT100 16GB 3.0 (2307). After following the japanese guy tutorial, I did Hello World on my new badusb and after that I tried to change the text. I converted the code with duckenconder and did the same thing of the original hello world but when I connect my USB on the port I get the unknown device error. I've tried to pin 2 and 3 to bootmode but I still get the same error. Is there a way to repair this ?
![89bd3956-68af-4e2b-a221-70a2ab8df7d9](https://user-images.githubusercontent.com/35127424/41264810-2b3a3836-6dc5-11e8-99fe-95f9a1619b30.jpg)

**Comment by nunofaria007** [comment]
Short pins 26 and 27 to enter BootMode

![short](https://user-images.githubusercontent.com/5213601/45266323-494e0280-b451-11e8-982d-83da39f70811.png)

**Comment by SrMilton** [comment]
Sorry, 2 and 3 = 26 and 27. Still the same ;/

**Comment by nunofaria007** [comment]
Strange, i have a 2307 and no matter how many times i brick it i can allways enter boot mode by shorting the pins.

**Comment by nunofaria007** [comment]
Just to be sure, are you shorting the pins as you plug the device, or are you trying to short them after plugging?

**Comment by SrMilton** [comment]
I'm shorting the pins and after I connect the device with the pins shorted

**Comment by SrMilton** [comment]
Is it common notify me as "Unknown device" but works fine on Drivecom ?

**Comment by nunofaria007** [comment]
Yes, it happened the same to me, if you go to Device Manager and change the drivers from Composite to Mass Storage you'll see that the device is recognized with no problems. I guess there is some trouble with the descriptors. I managed to get this to work after removing the Mass Storage Device interface and it's endpoints from the descriptor in the source code, so the device will be recognized only as a keyboard and not as a composite device. The downside is that i lost the ability to send SCSI commands (now i need to short the pins every time i want to jump to BootMode). In your case, if you can communicate with the device using DriveCom, then you can put it in BootMode and use MPALL to burn the official firmware.
