### ISSUE TITLE
Where is the CFW.bin?

### ISSUE THREAD

**Issue by double-pulsar** [brandonlw/Psychson#21]
Where is CFW.bin?
In Running Demo 1 (HID Payload),you write the command:
copy CFW.bin hid.bin
tools\EmbedPayload.exe inject.bin hid.bin
but where is the CFW.bin? where can I download it? thanks

**Comment by faridtm** [comment]
i have same problem ? where is the CFW.bin file ???

**Comment by Gaara4** [comment]
I use the FW.bin and it works to.

**Comment by double-pulsar** [comment]
@Gaara4，Did you success?Use FW.bin

**Comment by cubic3d** [comment]
1. Duplicate of #7. Look for issues first, before you open new.
2. There is no _cfw.bin_ in build.bat, it's _fw.bin_.

**Comment by andrei-cb** [comment]
https://github.com/adamcaudill/Psychson/releases

**Comment by double-pulsar** [comment]
@Caydenz thanks

**Comment by k3rw1n** [comment]
you can build it by running the build.bat under the /patch after you install the SDCC.

**Comment by faridtm** [comment]
thanks alot.

**Comment by aminazek** [comment]
CFW.bin is in the release section. 
https://github.com/adamcaudill/Psychson/releases

Everything has been compiled for you. 

BTW, any difference between CFW.bin and fw.bin?

**Comment by brandonlw** [comment]
No, it was just renamed to avoid confusion with any fw.bin you may have...which evidently wasn't accomplished. :)
