### ISSUE TITLE
DeviceIoControl Failed: 0079

### ISSUE THREAD

**Issue by jhuber-de** [brandonlw/Psychson#23]
I've got a Kingston DataTraveler 111 8GB which has the 2003 chip. (just to confirm it as supported divice)

I backed the original FW up and tried to reflash it to see if it works. I've got this as output:

C:\Users***\Desktop\BadUSB>tools\DriveCom.exe /drive=L /action=SendFirmware /burner="2251-03\Firmware PS2251-03\BN03V104M.BIN" /firmware=fw.bin
Action specified: SendFirmware
Gathering information...
Reported chip type: 2303
Reported chip ID: 98-DE-98-92-72-D7
Reported firmware version: 1.01.53
Mode: Firmware
Switching to boot mode...
Rebooting...
Sending firmware...
Executing...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0079
   bei DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byt
e[] data, Int32 bytesExpected) in c:\Users\Brandon\Documents\GitHub\PS2251-03\Dr
iveCom\DriveCom\PhisonDevice.cs:Zeile 365.
   bei DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Byte[] data) in c:\Users\Br
andon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 314.
   bei DriveCom.PhisonDevice.SendCommand(Byte[] cmd) in c:\Users\Brandon\Documen
ts\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 304.
   bei DriveCom.PhisonDevice.JumpToPRAM() in c:\Users\Brandon\Documents\GitHub\P
S2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 228.
   bei DriveCom.Startup._RunFirmware(String fileName) in c:\Users\Brandon\Docume
nts\GitHub\PS2251-03\DriveCom\DriveCom\Startup.cs:Zeile 439.
   bei DriveCom.Startup._SendFirmware() in c:\Users\Brandon\Documents\GitHub\PS2
251-03\DriveCom\DriveCom\Startup.cs:Zeile 378.
   bei DriveCom.Startup.Main(String[] args) in c:\Users\Brandon\Documents\GitHub
\PS2251-03\DriveCom\DriveCom\Startup.cs:Zeile 114.

Now the drive wont show up in the explorer even with show empty drives enabled.

I tried GetInfo with this output:

C:\Users***\Desktop\BadUSB>tools\DriveCom.exe /drive=L /action=GetInfo
Action specified: GetInfo
Gathering information...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0006
   bei DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byt
e[] data, Int32 bytesExpected) in c:\Users\Brandon\Documents\GitHub\PS2251-03\Dr
iveCom\DriveCom\PhisonDevice.cs:Zeile 365.
   bei DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Int32 bytesExpected) in c:\
Users\Brandon\Documents\GitHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile
 295.
   bei DriveCom.PhisonDevice.RequestVendorInfo() in c:\Users\Brandon\Documents\G
itHub\PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 140.
   bei DriveCom.PhisonDevice.GetChipType() in c:\Users\Brandon\Documents\GitHub\
PS2251-03\DriveCom\DriveCom\PhisonDevice.cs:Zeile 170.
   bei DriveCom.Startup._GetInfo() in c:\Users\Brandon\Documents\GitHub\PS2251-0
3\DriveCom\DriveCom\Startup.cs:Zeile 384.
   bei DriveCom.Startup.Main(String[] args) in c:\Users\Brandon\Documents\GitHub
\PS2251-03\DriveCom\DriveCom\Startup.cs:Zeile 104.

At least I tried SendFirmware after set the bootmode manualy (at least I hope so ther isn't light that indicate if its in bootmode) and I've got this:

C:\Users***\Desktop\BadUSB>tools\DriveCom.exe /drive=L /action=SendFirmware f
irmware /fw.bin
FATAL: System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereich
s.
   bei DriveCom.Startup.Main(String[] args) in c:\Users\Brandon\Documents\GitHub
\PS2251-03\DriveCom\DriveCom\Startup.cs:Zeile 71.

I there any change to revive the drive or is it foerver gone?

**Comment by cubic3d** [comment]
At `FATAL: System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.` you forgot to set a burner.

Every other questions and problems you listed are duplicates and have already opened or closed issue tickets. Please read them first. Keep in mind: This is a research project, no one can predict what will work and how this will work on different devices and firmware versions.
