### ISSUE TITLE
EmbedPayload Signature Not Found

### ISSUE THREAD

**Issue by gwlim** [brandonlw/Psychson#29]
Hi when I execute embedpayload.exe inject.bin hid.bin
I get 
Signature Not Found!
Is the hid.bin still safe to flash?

**Comment by ka1ias** [comment]
Hi, you are using a wrong hid.bin
https://github.com/adamcaudill/Psychson/issues/21

However I recommend to read all the posts as it seems that  after a first successful flash the chip will be unable to communicate to "drivecom"  again and you need to wreck the housing to get to the pins. Its all the errors DeviceIoControl failed.
Better wait until someone fine tunes the firmware...

**Comment by ghost** [comment]
I created a custom firmware from a original firmware executing build.bat in patch folder. No errors. but merging it with inject.bin does not work. I still get Signature not found.

**Comment by cubic3d** [comment]
You are mixing things up.
You can build a custom firmware by running _build.bat_ from _/firmware_.
Or you can patch your original firmware by running _build.bat_ from _/patch_.
You can _not_ inject Rubber Ducky bins into a patched firmware; only custom!

**Comment by ghost** [comment]
Now I got a hello world working, thank you.
