### ISSUE TITLE
Error when trying to open project (DriveCom) in visual studio

### ISSUE THREAD

**Issue by delpereth** [brandonlw/Psychson#30]
Hi,
I am trying to open the project file for drivecom in visual studio express 2012, and I get several errors:

DriveCom.csproj: Fehler in Zeile 5. "SYSTEM or PUBLIC" erwartet, aber ">" gefunden.
(Error in Line 5,  "SYSTEM or PUBLIC" expected but was ">")
and
Cant load Project File, unexpected Token found in Line 33, Position 71. Expected "=" but was ">"

I get those errors in German, so I just translated it.
I would like to compile it, but I even dont get the chance to load the project.

Anyone here who can help?
Thx

Del.

**Comment by ghost** [comment]
You downloaded all files at https://github.com/adamcaudill/Psychson/tree/master/DriveCom and opened DriveCom.sln in VSE2012? Worked for me without problems. Even in German ;)

**Comment by delpereth** [comment]
Yes I did, the error keeps appearing. As I dont have any USB 3.0 sticks here, I now deinstalled all again. Hopefully there will be some USB 2.0 tutorials and possibilities soon as I got a shitload of old sticks here :dancer:
