### ISSUE TITLE
CFW.bin versus FW.bin

### ISSUE THREAD

**Issue by aminazek** [brandonlw/Psychson#32]
I can build fw.bin by executing build.bat. However I can also use CFW.bin, which can be obtained from "release" section.

What is the difference between these 2 firmware? Are they the same?

**Comment by cubic3d** [comment]
Look at MD5 hashes:

```
b021e5a2315b7a9aeb5299c30d56b9f9  CFW.bin
b021e5a2315b7a9aeb5299c30d56b9f9  fw.bin
```

NO difference. Just named like that to prevent mixing it up with the dumped firmware.
