### ISSUE TITLE
errors when reflashing unmodified firmware

### ISSUE THREAD

**Issue by ghost** [brandonlw/Psychson#34]
I dumped a firmware (1.03.53) and then reflashed it without altering.
I get this error:

Action specified: SendFirmware
Gathering information...
Reported chip type: 2303
Reported chip ID: herebeID
Reported firmware version: 1.03.53
Mode: Firmware
Switching to boot mode...
FATAL: System.InvalidOperationException: DeviceIoControl failed: 0079
   at DriveCom.PhisonDevice._SendCommand(SafeFileHandle handle, Byte[] cmd, Byte
[] data, Int32 bytesExpected) in c:\Users\USER\Desktop\Psychson-master\Psyc
hson-master\DriveCom\DriveCom\PhisonDevice.cs:line 365
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd, Byte[] data) in c:\Users\USER\Desktop\Psychson-master\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs
:line 314
   at DriveCom.PhisonDevice.SendCommand(Byte[] cmd) in c:\Users\USER\Deskto
p\Psychson-master\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 304
   at DriveCom.PhisonDevice.JumpToPRAM() in c:\Users\USER\Desktop\Psychson-
master\Psychson-master\DriveCom\DriveCom\PhisonDevice.cs:line 228
   at DriveCom.Startup._ExecuteImage(String fileName) in c:\Users\USER\Desk
top\Psychson-master\Psychson-master\DriveCom\DriveCom\Startup.cs:line 404
   at DriveCom.Startup._SendFirmware() in c:\Users\USER\Desktop\Psychson-ma
ster\Psychson-master\DriveCom\DriveCom\Startup.cs:line 375
   at DriveCom.Startup.Main(String[] args) in c:\Users\USER\Desktop\Psychso
n-master\Psychson-master\DriveCom\DriveCom\Startup.cs:line 114

**Comment by cubic3d** [comment]
#9 #14 #5 try different burner maybe

**Comment by ghost** [comment]
I don't know...
I used this burner for flashing the 1.03.54 firmware, I think its the right one.

**Comment by ghost** [comment]
It is a SanDisk Ultra 16Gb USB 3.0.
It contains a compatible phison, but the label says SanDisk and before first flashing the firmware was 3.xxx but not 1.xxx as in the firmware file.

Does anybody dumped the original Firmware of a Sandisk Ultra 16 Gb and could upload it here?

**Comment by ghost** [comment]
I got it working again.
Burner BN03V114M.BIN
Firmware FW03FF01V10810M.BIN
MPALL 3.72.0B

**Comment by double-pulsar** [comment]
@Gott Are you test the Demo 1 (HID Payload) successed?Use SanDisk Ultra 16Gb cz48?thanks

**Comment by ghost** [comment]
I think we have the same stick, although I do not have the "cz48". pics on google are the same.
And no I did not manage to get it working.
The devs only reverse engineered 1.03.53 firmware, the Sandisk is not working with this.
My Sandisk is not working, perhaps another one could, although I think the known devices page should be updated to have a "User reported not working" list.
Currently I simply made the stick working again as a USB stick but not with BadUSB.

**Comment by mertsarica** [comment]
Hey @ghost

I bought the same USB and the firmware is 1.08.53 not 3.x. How can I downgrade it to 1.03.53 and verify it ?

![sandisk](https://cloud.githubusercontent.com/assets/4024184/4700820/8cc8c668-5851-11e4-82e5-554f610b2aa9.jpg)

Regards,

**Comment by double-pulsar** [comment]
@mertsarica Are you use  SanDisk Ultra 16Gb cz48?thanks

**Comment by mertsarica** [comment]
Yup but bricked it yesterday, will buy a new one in a couple days :)

**Comment by mertsarica** [comment]
I've purchased two more. Any idea how to downgrade it from 01.08.53 to 1.03.53 ?

Regards,

**Comment by double-pulsar** [comment]
@mertsarica I have no idea,cz48 is 0000 when I use "getinfo" command,and chipgenius read it is "UNKNOWN",WTF
