### ISSUE TITLE
How to read info, read some payload string using deviceiocontrol?

### ISSUE THREAD

**Issue by skunit** [brandonlw/Psychson#38]
SO for example i wrote custom payload, which contains only string, and injected it into phison firmware, now i would like to make an app to read this string using deviceiocontrol, how can i do it?

**Comment by brandonlw** [comment]
You can't as it is. You could add a handler for a custom SCSI command to the code that would send whatever string you like back to the PC. Then you can use the SendCommand() method in DriveCom (which uses DeviceIoControl) to send it and read the response.
