### ISSUE TITLE
Revert from HID (Demo 1)

### ISSUE THREAD

**Issue by ghost** [brandonlw/Psychson#39]
Demo 1, to emulate a keyboard (https://github.com/adamcaudill/Psychson#running-demo-1-hid-payload)  worked ok. However, since the "keyboard" now has no drive letter, how do I revert the USB stick to normal operation?

**Comment by bl4k1st** [comment]
Set Windows explorer to show hidden files, folders and drives.
Then you can see the drives letter, when connected.
Go into boot mode manually and flash firmware.

**Comment by ghost** [comment]
Thanks but I already have your suggested settings set. 
Did the shortcut and brought the USB back to life. Yet cannot have it act as a memory, only as keyboard.
I failed dumping original fw.bin.

**Comment by bl4k1st** [comment]
simply install the 1.03.53 firmware from the .rar file without altering.

**Comment by ghost** [comment]
I did that. No errors. Still reverts to HID when I do not shortcut.

**Comment by bl4k1st** [comment]
Tried that on my USB myself again, it is a normal USB stick with storage again.
Sorry, cannot help further, works for me :(
