### ISSUE TITLE
Kingston USB-Stick 3.0 - DataTraveler G4, 8GB

### ISSUE THREAD

**Issue by ChristophWieser** [brandonlw/Psychson#40]
Anyone experience with "Kingston USB-Stick 3.0 - DataTraveler G4, 8GB", does it work?

This Stick has a Phison 2251-07 (2307)

**Comment by brandonlw** [comment]
If it's 2251-07, it's not likely to work as is.

**Comment by crappy44** [comment]
I have the same and my has 2251-03

**Comment by bsfoolery** [comment]
make a video and up on youtube.

**Comment by crappy44** [comment]
A video? Just open the stick the number is printed on the chip.

**Comment by Zerokami** [comment]
I also have a Kingston USB-Stick 3.0 - DataTraveler G4, 8GB", with a Phison 2251-07 (2307) .

I opened up the case and it is a 07 not a 03.

**Comment by sristisravan** [comment]
@brandonlw Any work around methods for making PS2307 devices work as badUSB?
