### ISSUE TITLE
Is there a way to restore a dead USB stick to working order?

### ISSUE THREAD

**Issue by bsmathers** [brandonlw/Psychson#5]
Hi,

I tried sending a new firmware image to a Silicon Power Blaze 16 GB (with a PS2251-03), but apparently I did something wrong as DriveCom threw an error during the "Executing FIles" phase. Now, when I reinsert the USB, the stick does not light up, and neither the file browser nor Disk Management see a disk there. Is there any way to reflash new firmware to the USB and restore it to working order, or should I just write it off as dead?

**Comment by itdaniher** [comment]
If the disk no longer enumerates via USB (device manager on windows, `lsusb` on a "sane" OS) then it's probably dead and gone, and nothing short of a soldering iron and JTAG adapter will resurrect it.

**Comment by ghost** [comment]
In many cases you can short certain pins on the controller to force the device into boot mode, and send the stock firmware then. We talk about how this is done (briefly) in the talk video.

http://www.irongeek.com/i.php?page=videos/derbycon4/t510-making-badusb-work-for-you-adam-caudill-brandon-wilson

If you are unable to get it into boot mode, then it's really dead.

**Comment by brandonlw** [comment]
Shorting the pins is a finnicky thing. An explanation of how to do it correctly is here: https://github.com/adamcaudill/Psychson/wiki/Executing-From-Boot-ROM

It may take several tries before you get a feel for it.
