### ISSUE TITLE
Conclusion of bad usb.

### ISSUE THREAD

**Issue by bytedeez** [brandonlw/Psychson#58]
I have purchased a total of 5 known devices.
All have been 2307.
Conclusion: Manufacturers solution to badusb, which really started before badUSB was known of, is not a firmware patch but rather a chip upgrade.

**Comment by brandonlw** [comment]
That's a flawed conclusion -- the firmware on a 2307 can be updated just as easily as on a 2303. Someone with the time just needs to work out the (minor) differences in order to apply the same types of patches to it.

**Comment by bytedeez** [comment]
Hence the sarcasm in "which really started before badUSB was known of" .
