### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by question123** [brandonlw/Psychson#62]
Hey,
My question is, why I couldn't use my memory after flashing the firmware 

Thank you for your answers :)

**Comment by agd-media** [comment]
Because it is not configured as a memory drive anymore, but as a keyboard (when using the HID example)
With the others like the hidden partition patch, it should run as a memory stick (but with 2 partitions where 1 is hidden)

**Comment by question123** [comment]
Okay, thank you :)
