### ISSUE TITLE
USB 3.0 not supported

### ISSUE THREAD

**Issue by question123** [brandonlw/Psychson#63]
Hi,
I've only tested my usb drive on usb 2.0 ports. Yesterday, I realized, that the usb 3.0 port doesn't works with my drive.
Why is this happening????

**Comment by darf2k** [comment]
Does the Phison 2251-03 control chip support usb3.0? If it does not, you may not. Or, we should discover a new usb3.0 control chip~I think so.

**Comment by question123** [comment]
Sry, i've given up the project ;)
