### ISSUE TITLE
Can't find CFW.bin file

### ISSUE THREAD

**Issue by sdrinken** [brandonlw/Psychson#7]
I am trying to test the HID Payload but can’t find the CFW.bin file within any of the directories. Could you please let me know how or where I can obtain this file?
Thank you and kind regards,

**Comment by aspcartman** [comment]
I guess CFW.bin stands for CustomFirmWare.bin

Go to \firmware folder in cmd and run build.bat. It will, hopefully, build you a custom firmware. Rename resulting fw.bin to CFW.bin and continue.

BTW, do you have 2303 flash? Whats its vendor and model?

**Comment by sdrinken** [comment]
Thanks for clearing that up. I did already run the build.bat and saw the fw.bin being created. 
I thought the CFW.bin was a separate extra custom firmware file.

I ordered  two 8GB Supersonic Xpress (PSF8GXPUSB) drives to play with. I haven't received then yet so I don't know what firmware version they are at.

Thanks again!

**Comment by andrei-cb** [comment]
https://github.com/adamcaudill/Psychson/releases
