### ISSUE TITLE
Burner Image (general)

### ISSUE THREAD

**Issue by derBaecker94** [brandonlw/Psychson#74]
Hey everyone,

I just got a short general question. My device has the chip 2307 - so not supported (so far) and I'm going for another one soon.

But I actually wondered where to get the Burner Image, because I found none at all. Is it only available somewhere at that russian page? I'm not familial with the russian language at all and could not read it between the lines as well .. Where did you get yours from?

Thanks!

**Comment by WeldFire** [comment]
http://www.usbdev.ru/files/phison/
Do a Ctrl+F and search for "BN07"

**Comment by derBaecker94** [comment]
Thanks mate, so much easier to do when you know what you are looking for. :-)
