### ISSUE TITLE
USB 2.0 not supported

### ISSUE THREAD

**Issue by ghost** [brandonlw/Psychson#8]
Your Wiki says that All Phison-based USB 2.0 devices aren't supported.
Why?

**Comment by ghost** [comment]
The structure of the firmware for the USB 2.0 devices is fairly different; while it's possible to add support, it'll be quite a bit of effort. It's a lot of reverse engineering work that would need to be done.

Phison is only marketing the 3.0 controllers at this point, so we focused on those.

**Comment by ghost** [comment]
But there are much more USB 2.0's around than 3.0's. 

Isn't it a much bigger vulnerability to be able to reprogram USB 2.0's?

**Comment by ghost** [comment]
The same technique can be applied to several models of the USB 2.0 Phison controllers, but we chose to focus on the USB 3.0 model(s) for a couple reasons:
- Phison no longer markets the 2.0 controllers, not sure if they are still selling them though.
- The specs are better for the 3.0 devices, so there are more opportunities to do interesting things with the hardware.

We haven't decided if we will pursue versions for the 2.0 devices, but someone else certainly could.

**Comment by pascalpfeil** [comment]
But it says:
Devices known to be incompatible:
•All Phison-based USB 2.0 devices

https://github.com/adamcaudill/Psychson/wiki/Known-Supported-Devices

**Comment by brandonlw** [comment]
The firmware on those drives can be updated the same basic way that USB 3.0 drives are, but we haven't looked at them at all. I suspect the update method will vary some -- this project was only aimed at the 3.0 drives. If future research indicates that 2.0 drive support would be easy to add here, and would make sense to be here, then it will be -- otherwise it will stay 3.0-only.

**Comment by ghost** [comment]
Time for some Reverse Engineering I guess? ;D

**Comment by brandonlw** [comment]
Unfortunately yes. USB 2.0 support isn't being considered as viable for this project, so I'm going to close the issue.
